package hello.jdbc.exception;import static org.assertj.core.api.Assertions.*;import org.junit.jupiter.api.Test;import lombok.extern.slf4j.Slf4j;@Slf4jpublic class CheckedTest {	@Test	void checked() {		Client client = new Client();		assertThatThrownBy(() -> client.call())		.isInstanceOf(Exception.class);	}	static class Client {		public void call() throws Exception {			NetWorkService service = new NetWorkService();			service.call();		}	}	static class NetWorkService {		public void call() throws Exception {			NetworkRepository repository = new NetworkRepository();			repository.connection();		}	}	static class NetworkRepository {		void connection() throws Exception {			throw new Exception("ex");		}	}}